# Generated by Django 5.1.1 on 2024-10-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('arrv_time', models.CharField(max_length=10)),
                ('depart_time', models.CharField(max_length=10)),
                ('desti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trains.station')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trains.station')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('trains_rev', models.ManyToManyField(blank=True, related_name='passengers', to='trains.train')),
            ],
        ),
    ]
