# Generated by Django 5.1.1 on 2024-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='t_name',
            new_name='TrainName',
        ),
        migrations.AddField(
            model_name='train',
            name='TrainNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
