# Generated by Django 5.1.1 on 2024-10-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_rename_t_name_train_trainname_train_trainno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='TrainNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
