# Generated by Django 5.1.1 on 2024-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_remove_train_id_alter_train_trainno'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='TrainNo',
            field=models.IntegerField(),
        ),
    ]
